### ISSUE TITLE
eggdrop 1.9.0 compatible?

### ISSUE THREAD

**Issue by sacredland** [empus/armour#1]
eggdrop v1.9.0+serverlen -> Tcl error [arm:pubm:all]: invalid command name "arm:pubm:all"

**Comment by sacredland** [comment]
also tried on eggdrop 1.8.4 and same error appear

**Comment by empus** [comment]
As far as I'm aware, the latest stable version of eggdrop is 1.8.4.

I'll need more information about that error, but it suggests to me that the script hasn't loaded properly.  Probably because some other error occurred previously when trying to load.

**Comment by sacredland** [comment]
eggdrop is into /home/deb/  & armour is into /home/deb/armour
1) cd home/deb/armour 
2) ./makeconf.sh
usage: makeconf.sh <bot> "<chan>"
ensure channel is enclosed in "#quotes"
deb@wtf:~/deb/armour$ ./makeconf.sh deb "#test"
cp: cannot stat '../bot.conf.sample': No such file or directory
cp: cannot stat '../db/EDITME.chan.sample': No such file or directory
cp: cannot stat '../db/EDITME.user.sample': No such file or directory
sed: -e expression #1, char 1: unknown command: `.'
sed: -e expression #1, char 1: unknown command: `.'
rm: cannot remove 'deb.conf.bak': No such file or directory
sed: -e expression #1, char 1: unknown command: `.'
rm: cannot remove '../deb.conf.bak': No such file or directory
done
3) cd ..
4) from /home/deb 
./eggdrop deb.conf
[@] Armour: loading ./armour/armour-3.4.4.tcl ...
[@] Armour: loaded script configuration.
[@] Armour: eggdrop binds restructured.
[@] Armour: loaded command binds.
[@] error loading sqlite3 library.  unable to load Armour SQL DB functions.
[@] Armour: loading user database...
[@] Armour: loading ./armour/plugins/sk/armdb.tcl ...
[@] error loading sqlite3 library.  unable to load Armour SQL DB functions.
[@] Armour: loading ./armour/plugins/tell.tcl ...
[@] Armour: loaded plugin: tell
[@] Armour v Loaded (empus@undernet.org)
Userfile loaded, unpacking...
=== deb: 3 channels, 2 users.
Launched into the background  (pid: 22636)

on IRC: 
[20:34:45] <nick> deb: cmds
(from schat console:) <(s)deb> [20:34:45] Tcl error [arm:pubm:all]: invalid command name "arm:pubm:all"

**Comment by empus** [comment]
Ok, a couple of things here:

1). Don't use the makeconf.sh script.  That's just something I use as a cheat to quickly spawn new bots.  You don't have all the prerequisites.  Maybe I'll delete that script from the repository to avoid confusion!

2). Have you loaded the armour.conf file from your eggdrop config?  That will load the Armour TCL itself, don't load it directly.

3). You're getting an error that the sqlite3 TCL library can't be loaded so you'll need to install that on the machine.  Don't use the old file DB method as that will be removed at some point... best to get sqlite3 working :>

4). There have been some recent updates, so best use a more recent version.

**Comment by empus** [comment]
Feel free to ask in #armour on Undernet too, if that's easier

**Comment by empus** [comment]
Solved by installing sqlite3 library
